### ISSUE TITLE
command bee don't work from the terminal

### ISSUE THREAD

**Issue by pkhilmon** [sschmid/bee#2]
Hello,

I installed Bee with
```
bash -c "$(curl -fsSL https://raw.githubusercontent.com/sschmid/bee/master/install)"
```
Output from terminal
```
Cloning into '/usr/local/opt/bee'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 426 (delta 29), reused 53 (delta 19), pack-reused 356
Receiving objects: 100% (426/426), 466.89 KiB | 1.10 MiB/s, done.
Resolving deltas: 100% (173/173), done.
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

After that when I try ```bee``` in terminal. I got a message ```/usr/local/bin/bee: No such file or directory```

When I made clone through SourceTree and copied bee exec ```ln -s "/path_to_repo/libexec/bee" "usr/local/bin/bee"``` the ```bee``` works well.

I tested it couple of times, maybe something is wrong with my stuff, I don't know :).
(I updated git to the latest version)

Thanks for the great plugin.

**Comment by sschmid** [comment]
Hey, your output says
```
git-lfs filter-process: git-lfs: command not found
```
this mean you don't have git-lfs installed which is required

It works with sourcetree because it has git-lfs bundled with the app.

If you want to try installing bee from scratch again, please intsall git-lfs first and delete
```
/usr/local/opt/bee
/usr/local/bin/bee
```

**Comment by pkhilmon** [comment]
Oh, I don't know about git-lfs.
 
Everything works perfect now.

Thanks.

**Comment by sschmid** [comment]
Great to hear! Happy coding!
